# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iospec_pre', models.TextField()),
                ('iospec_post', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('answer_key', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('iospec_pre', models.TextField()),
                ('iospec_post', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='grader',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_io.Question'),
        ),
    ]
