# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_io', '0002_auto_20170312_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('source', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('post_grade', models.BooleanField()),
                ('concluded', models.BooleanField(default=bool)),
                ('finished', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='grader',
            old_name='num_expansiosn',
            new_name='num_expansions',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='num_expansiosn',
            new_name='num_expansions',
        ),
        migrations.AddField(
            model_name='gradingjob',
            name='grader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_io.Grader'),
        ),
    ]
