# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_io', '0004_auto_20170314_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='grader',
            name='usable',
            field=models.BooleanField(default=bool),
        ),
        migrations.AlterField(
            model_name='grader',
            name='iospec_pre',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='iospec_pre',
            field=models.TextField(blank=True),
        ),
    ]
