# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_io', '0006_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingjob',
            name='result_data',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='gradingjob',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
