# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_io', '0008_gradingjob_running'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_key',
            new_name='source',
        ),
    ]
